services:
  inventory_db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=inventory'
      - 'MYSQL_PASSWORD=oracle'
      - 'MYSQL_ROOT_PASSWORD=oracle'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
